# Generated by Django 5.2.6 on 2025-09-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_message_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_deliver',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
