# Generated by Django 5.2.6 on 2025-09-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_message_message_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
